#pragma once
#include "yanyun_appearance.h"
namespace studio033 {
inline const char* L(const char* text){
 if(!text)return "";
 struct Pair{const char* zh;const char* en;};
 static constexpr Pair pairs[]={
 {"人物识别延迟过高，分区尚未生效","Character detection is too late; regional processing is inactive."},
 {"画面已变化，等待重新识别","Frame identity changed; waiting for a new character mask."},
 {"人物与场景分区已录制","Character / scene regions recorded."},
 {"人物分区平滑过渡中","Character regions are blending in smoothly."},
 {"人物新参数准备中，暂用上一套人物参数","Preparing new character settings; the previous character settings stay in use."},
 {"识别失败：人物 / 场景参数及预览当前未生效，原画保留。","Detection failed: regional controls and preview are inactive. Original image retained."},
 {"人物 / 场景方案尚未应用；识别预览可独立开关。","Regional recipe not applied. Mask preview is an independent switch."},
 {"开启 NR 后可以预览识别区域。","Enable NR to preview the character mask."},
 {"参数尚未应用，请点击应用修改。","Changes pending. Click Apply changes."},
 {"本层未启用；请先在上方选择对应层数。","Inactive layer. Select the layer count above first."},

 {"等待参数就绪","Waiting for controls"},
 {"写实","Realistic"},
 {"还原","Original"},
 {"自定义","Custom"},
 {"全局","Global"},
 {"人物","Character"},
 {"场景","Scene"},
 {"人物 / 场景","Character / Scene"},
 {"应用修改","Apply changes"},
 {"应用方案","Apply preset"},
 {"有未应用的修改","Unapplied changes"},
 {"前置、SR、NR 共用同一份方案；点击应用后统一生效。","Color, SR and NR share one preset. Apply to activate all changes."},
 {"%s精度超限：请在 SR 页调到 %d%% 以内。","%s precision exceeds the limit. Set it to %d%% or less in SR."},
 {"保留原值","Keep current value"},
 {"当前模式使用本列","This column is active"},
 {"当前模式不使用本列，参数保留","Inactive column; values are retained"},
 {"已收起，参数保留。点击切换处理模式。","Collapsed; values are retained. Click to switch processing mode."},
 {"%d 层","%d layers"},
 {"第 %d 层","Layer %d"},
 {"启用","On"},
 {"未启用","Off"},
 {"默认","Default"},
 {"自然","Natural"},
 {"电影","Cinematic"},
 {"整体强度","Overall intensity"},
 {"细节强度","Detail"},
 {"局部明暗","Local contrast"},
 {"全局色调","Color tone"},
 {"皮肤质感","Skin texture"},
 {"模型肤色保护","Model skin-color protection"},
 {"界面校正：暂无独立界面输入","UI correction: no separate UI input"},
 {"当前接入没有提供 UI 图层；保留方案兼容值，不把它显示为可生效开关。","A separate UI layer is unavailable. The stored value is retained for preset compatibility."},
 {"混合与颜色","Mix and color"},
 {"效果混合 %","Effect mix %"},
 {"模型颜色","Model color"},
 {"0 为不叠加 NR 改动，100 为正常强度，200 为增强改动；不改变模型处理精度。","0 applies no NR change; 100 is normal; 200 amplifies the change. Processing resolution is unchanged."},
 {"0 主要保留明暗变化，1 同时保留模型带来的颜色变化；不是饱和度。","0 mainly keeps luminance changes; 1 also keeps model color changes. This is not saturation."},
 {"保存与分享","Save and share"},
 {"保存方案","Save preset"},
 {"读取方案","Load preset"},
 {"生成代码","Create code"},
 {"复制","Copy"},
 {"导入为草稿","Import draft"},
 {"生成分享码","Create share code"},
 {"切换","Switch"},
 {"删除","Delete"},
 {"确认删除","Confirm delete"},
 {"还没有保存记录。点「保存方案」会在这里留下一条。","No saved records yet. Save preset leaves one here."},
 {"保存记录（名字可直接改）","Saved records (names can be edited)"},
 {"已存为一条新记录，名字可以直接改。","Saved as a new record; you can rename it."},
 {"保存记录已满（40 条），请先删除不用的。","Records are full (40); delete one first."},
 {"已删除这条记录。","Record deleted."},
 {"改名未能保存，请重试。","The new name could not be saved; please retry."},
 {"之前保存的方案","Earlier saved preset"},
 {"保存记录暂时读不到，请稍后再试。","Saved records can't be read right now; try again shortly."},
 {"删除失败，这条记录还在。","Couldn't delete; the record is still there."},
 {"已导入，应用后生效。","Imported. Apply to activate."},
 {"代码不兼容或损坏，原方案已保留。","The code is incompatible or damaged. Your preset is unchanged."},
 {"已读取草稿，应用后生效。","Draft loaded. Apply to activate."},
 {"草稿已保存，尚未应用。","Draft saved; not applied yet."},
 {"方案已保存。","Preset saved."},
 {"保存失败，原方案已保留。","Save failed. The previous preset is retained."},
 {"关闭 NR","Disable NR"},
 {"开启 NR","Enable NR"},
 {"本次 NR 已暂停","NR paused for this session"},
 {"NR 出现异常","NR error"},
 {"正在准备模型","Preparing models"},
 {"NR 处理中","NR processing"},
 {"等待画面","Waiting for input"},
 {"NR 已关闭","NR disabled"},
 {"%s 切换 NR；Home / Shift+退格打开面板；Shift+F9 开关监控。","%s: toggle NR. Home / Shift+Backspace: panel. Shift+F9: monitor."},
 {"按新键…","Press a key…"},
 {"按想用的键：字母、数字、符号、F1 到 F12、方向键、Insert、Delete、End、PageUp、PageDown、小键盘，或者鼠标中键、侧键；Esc 取消。","Press the key to use: a letter, digit or symbol, F1 to F12, an arrow, Insert, Delete, End, PageUp, PageDown, the keypad, or the middle / side mouse button; Esc cancels."},
 {"开关 NR 的快捷键。点一下，再按想用的键（大多数键和鼠标中键、侧键都行）就换成它。","The key that turns NR on and off. Click, then press the key you want (most keys and the middle / side mouse buttons work)."},
 {"方向键左","Left"},{"方向键上","Up"},{"方向键右","Right"},{"方向键下","Down"},
 {"鼠标中键","Mouse 3"},{"鼠标侧键1","Mouse 4"},{"鼠标侧键2","Mouse 5"},
 {"Home 用来打开面板，请换一个键。","Home opens the panel; choose another key."},
 {"退格键打字要用，Shift+退格还用来打开面板，请换一个键。","Backspace is for typing and Shift+Backspace opens the panel; choose another key."},
 {"回车、空格、Tab 打字和游戏里都要用，请换一个键。","Enter, Space and Tab are needed for typing and in the game; choose another key."},
 {"CapsLock、NumLock 会切换键盘状态，请换一个键。","Caps Lock and Num Lock switch the keyboard state; choose another key."},
 {"PrintScreen 是 Windows 截屏键，请换一个键。","Print Screen is the Windows screenshot key; choose another key."},
 {"Pause 键按下和松开是同一瞬间发出的，游戏里认不出来，请换一个键。","Pause sends its press and release at the same moment, so the game never sees it held; choose another key."},
 {"Shift、Ctrl、Alt、Win 不能单独当开关键，请换一个键。","Shift, Ctrl, Alt and Win cannot be the key on their own; choose another key."},
 {"按着 Shift 时不算，Shift+F9 仍是监控。"," Not while Shift is held: Shift+F9 stays the monitor."},
 {"在游戏里打字时按到它也会切换 NR。"," Typing it in the game also switches NR."},
 {"小键盘要开着 NumLock 才认。"," Keypad keys need Num Lock on."},
 {"Shift+F9  显示 / 隐藏监控","Shift+F9  Show / hide monitor"},
 {"人物识别","Character detection"},
 {"人物保真","Character fidelity"},
 {"场景强度","Scene intensity"},
 {"边缘柔化","Edge feathering"},
 {"显示人物识别区域","Show character mask"},
 {"第 1 层精度 %","Layer 1 precision %"},
 {"第 2 层精度 %","Layer 2 precision %"},
 {"第 3 层精度 %","Layer 3 precision %"},
 {"对应 NR 的同一层；是否启用由 NR 页的层数决定。","Matches the same NR layer. Active layers are selected in NR."},
 {"更多","More"},
 {"以输出分辨率为基准","Use output resolution"},
 {"开启：以最终输出尺寸计算精度；关闭：以游戏渲染尺寸计算。两者相同时不会改变结果。","On: use output size as the precision basis. Off: use render size. Equal sizes produce the same result."},
 {"最终清晰度","Final sharpness"},
 {"NR 合成完成后增强边缘，与运动自适应锐化分开。","Sharpen edges after NR composition; separate from motion-adaptive sharpening."},
 {"运动自适应锐化","Motion-adaptive sharpening"},
 {"静止强度","Still intensity"},
 {"运动强度","Motion intensity"},
 {"运动阈值","Motion threshold"},
 {"SR 精度对应 NR 每层；游戏自带的 DLSS 超分档位仍在游戏设置中调整。","SR precision applies to each NR layer. Native DLSS quality is selected in the game settings."},
 {"启用前置调色","Enable input color grading"},
 {"中性","Neutral"},
 {"柔和","Soft"},
 {"动漫色阶","Anime"},
 {"风格强度","Style intensity"},
 {"曝光","Exposure"},
 {"对比度","Contrast"},
 {"饱和度","Saturation"},
 {"冷暖","Temperature"},
 {"色偏","Tint"},
 {"高光","Highlights"},
 {"作者 B站@热心网友033","Author Bilibili @热心网友033"},
 {"拖动数值，或 Ctrl 点击输入并按 Enter 确认。","Drag the value, or Ctrl-click to type and press Enter."},
 {"神经渲染已暂停","Neural rendering paused"},
 {"已安排下次恢复。请正常退出游戏后重新启动，当前这局仍暂停。","Recovery is scheduled for the next launch. Exit and restart the game normally; this session remains paused."},
 {"检测到连续未完成的启动记录，本次暂未开启神经渲染。","Repeated incomplete launches were detected. Neural rendering is paused for this session."},
 {"下次启动恢复","Recover on next launch"},
 {"恢复记录未能保存，请检查游戏目录写入权限后重试。","Could not save the recovery request. Check folder write permissions and retry."},
 {"帧生成","Frame generation"},
 {"原生多帧倍率","Native frame multiplier"},
 {"跟随游戏","Follow game"},
 {"游戏帧生成当前关闭","Game frame generation is off"},
 {"运行库接受   %u×%s","Runtime accepted   %u×%s"},
 {"（与请求不一致）"," (differs from request)"},
 {"请求 %u× 尚未生效。%s","Requested %u× is not active. %s"},
 {"节奏验证未通过，保留游戏原有请求。","Pacing validation failed; retaining the game request."},
 {"等待游戏重新提交帧生成设置；可在游戏中关闭帧生成再开启。","Waiting for the game to resubmit settings. Toggle frame generation off and on in the game."},
 {"等待游戏帧生成运行库反馈","Waiting for frame-generation runtime feedback"},
 {"GPU 原生帧耗时   %.1f ms","Native GPU frame   %.1f ms"},
 {"其中神经渲染   %.1f ms","Neural rendering   %.1f ms"},
 {"尚未收到游戏的帧生成接口：在游戏设置里打开 DLSS 帧生成后再看。","The game has not offered its frame generation yet: turn on DLSS Frame Generation in the game settings, then look again."},
 {"随包的帧生成转接件没装上：用 033 安装器重新安装一次；还是没有，把安装报告发给作者。","The bundled frame-generation bridge is not installed: run the 033 installer again; if it is still missing, send the install report to the author."},
 {"Windows 的「硬件加速 GPU 计划」没开，游戏会把帧生成选项藏起来。打开方法：Windows 设置里搜「图形设置」，打开「硬件加速 GPU 计划」，然后重启电脑。","Windows hardware-accelerated GPU scheduling is off, so the game hides frame generation. Search Windows Settings for \"Graphics settings\", turn on hardware-accelerated GPU scheduling, then restart the PC."},
 {"没查到「硬件加速 GPU 计划」的设置：Windows 设置里搜「图形设置」，确认它是打开的（改完要重启电脑）。","Hardware-accelerated GPU scheduling could not be read: search Windows Settings for \"Graphics settings\" and make sure it is on (a change needs a restart)."},
 {"Windows 版本太旧：游戏的帧生成要 Windows 10 2004 或更新。","Windows is too old: the game's frame generation needs Windows 10 2004 or newer."},
 {"转接件已装，「硬件加速 GPU 计划」已开。游戏里还是没有帧生成选项的话：把游戏目录里 dlssg_to_fsr3.ini 的 EnableLogging 改成 1，进一次游戏，把 dlssg_to_fsr3.log 发给作者。","The bridge is installed and GPU scheduling is on. If the game still shows no frame generation: set EnableLogging to 1 in dlssg_to_fsr3.ini in the game folder, start the game once and send dlssg_to_fsr3.log to the author."},
 {"需要游戏自身提供 DLSS 帧生成。倍率不代表输入延迟；低延迟与其他帧生成选项位于设置。","Requires native DLSS frame generation. The multiplier is not a measure of input latency."},
 {"20 系","RTX 20 series"},
 {"30 系","RTX 30 series"},
 {"40 系","RTX 40 series"},
 {"50 系","RTX 50 series"},
 {"这张显卡","This GPU"},
 {"NVIDIA 原生 DLSS-G","NVIDIA native DLSS-G"},
 {"插帧引擎","Frame-generation engine"},
 {"Intel XeSS（本包未附带）","Intel XeSS (not bundled)"},
 {"插帧倍率","Frame multiplier"},
 {"写入 dlssg_to_fsr3.ini 失败，设置未改变；请确认游戏目录可写。","Could not write dlssg_to_fsr3.ini. Settings are unchanged; check folder write permissions."},
 {"已写入 dlssg_to_fsr3.ini，退出游戏重进后生效。","Saved to dlssg_to_fsr3.ini. Restart the game to activate."},
 {"这是旧版转接件（v0.4x，只有 FSR3.1）。用 033 安装器重新安装可升级到原生 DLSS-G。","Legacy bridge v0.4x supports FSR3.1 only. Reinstall with the 033 installer to update."},
 {"配置文件指定了 XeSS（FGMode=1），本包没有附带 XeSS 组件，请改选上面两种引擎之一。","The configuration selects XeSS (FGMode=1), which is not bundled. Select one of the supported engines above."},
 {"缺少 %s，原生 DLSS-G 无法加载；请用 033 安装器重新安装，或改用 FSR3.1。","Missing %s; native DLSS-G cannot load. Reinstall with 033 or select FSR3.1."},
 {"20 系的原生 DLSS-G 路线，转接件作者尚未在真卡上验证；如果黑屏、闪退或画面异常，把引擎改成 FSR3.1。","The bridge author has not validated native DLSS-G on an RTX 20 GPU. Select FSR3.1 if it fails."},
 {"在游戏设置里打开 DLSS 帧生成，转接件会接管这个开关。倍率越高，真实帧占比越低；只用于单机游戏。","Enable DLSS frame generation in the game settings. Higher multipliers contain a smaller proportion of rendered frames. Single-player use only."},
 {"转接件入口：%s","Bridge entry: %s"},
 {"%s的多帧生成由随包的 nvidia_mfg_bridge 转接件提供。这个游戏自带 DLSS 帧生成，但目录里没有转接件；用 033 安装器重新安装即可放入。","%s uses the bundled nvidia_mfg_bridge for multi-frame generation. The bridge is missing; reinstall with 033."},
 {"%s的多帧生成需要游戏自带 DLSS 帧生成，这个游戏没有。","%s multi-frame generation needs the game's own DLSS frame generation; this game has none."},
 {"运行状态","Runtime status"},
 {"日志：dlss5-033.log","Log: dlss5-033.log"},
 {"未读取到兼容方案；当前草稿已保留。","No compatible preset was loaded. Your draft is retained."},
 {"方案已提交，正在准备模型；生效状态见上方。","Preset submitted. Preparing models; see activation status above."},
 {"提交失败，草稿已保留，请重试。","Submission failed. Your draft is retained; retry."},
 {"NR 命令记录 %llu","NR command records: %llu"},
 {"原生引导已用于记录：%s；同次求值：%s。","Native guides recorded: %s; same evaluation: %s."},
 {"是","Yes"},
 {"尚无记录","No record"},
 {"未证明","Unproven"},
 {"命令已记录不代表屏幕实际显示或画质验收通过。","Recorded commands do not prove displayed output or visual acceptance."},
 {"共用设置：加载 %d · 调色保存 %d · NR 保存 %d · FG 保存 %d","Settings: load %d; color save %d; NR save %d; FG save %d"},
 // S32: 模式一 / 模式二 and 超分模型.
 {"模式一","Mode 1"},
 {"模式二","Mode 2"},
 {"模式一：人物和场景各自把整张画面算一遍，人物可以单独调模型参数。","Mode 1: characters and scene each process the whole picture; characters have their own model settings."},
 {"模式二：全局第 1 层整张画面只算一次，人物区域停在这一层，场景区域接着叠第 2、3 层；比模式一少算一整遍。","Mode 2: the global first layer runs once over the whole picture; characters stop there and the scene continues with layers 2 and 3. One full pass less than mode 1."},
 {"人物停在全局第 1 层；这里只调它的强弱和颜色。","Characters stop at the global first layer; set only its strength and colour here."},
 {"第 1 层：人物和场景共用","Layer 1: shared by characters and scene"},
 {"第 1 层在全局栏，人物和场景共用","Layer 1 is in the global column, shared by characters and scene"},
 {"按全局第 1 层的尺寸算；是否启用由 NR 页的层数决定。","Relative to the global first layer; the NR page's layer count decides whether it runs."},
 {"人物用全局第 1 层的精度。","Characters use the global first layer's precision."},
 {"正在准备模式二（第 1 层人物和场景共用）","Preparing mode 2 (layer 1 shared by characters and scene)"},
 {"等待第 1 层结果，暂用场景效果","Waiting for the first layer; scene look shown"},
 {"等待第 1 层模型就绪","Waiting for the first-layer model"},
 {"第 1 层尺寸超出范围，分区尚未生效","First-layer size out of range; regions are inactive"},
 {"超分模型","SR model"},
 {"游戏默认","Game default"},
 {"K（低）建议 20 系、30 系启用","K (low): recommended for RTX 20 / 30"},
 {"M（中）40 系、50 系可启用","M (medium): for RTX 40 / 50"},
 {"L（高）40 系、50 系可启用","L (high): for RTX 40 / 50"},
 {"K（低）","K (low)"},
 {"M（中）","M (medium)"},
 {"L（高）","L (high)"},
 {"游戏自带的 DLSS 超分用哪个模型；换模型时超分会重建一次，画面会顿一下。选 K、M、L 时游戏都按质量档分辨率渲染，游戏默认按游戏自己的档位；游戏设置里显示的档位不变。","Which model the game's own DLSS Super Resolution uses. Changing it rebuilds DLSS once; the picture pauses briefly. K, M and L all render at the Quality size, game default at the game's own mode; the game's settings menu keeps showing its own mode."},
 {"要换成质量档分辨率：在游戏设置里把 DLSS 档位切一下再切回来，或重进游戏。","To switch to the Quality size, change the game's DLSS mode once and back, or restart the game."},
 {"要换成平衡档分辨率：在游戏设置里把 DLSS 档位切一下再切回来，或重进游戏。","To switch to the Balanced size, change the game's DLSS mode once and back, or restart the game."},
 {"要回到游戏自己的分辨率：在游戏设置里把 DLSS 档位切一下再切回来，或重进游戏。","To return to the game's own size, change the game's DLSS mode once and back, or restart the game."},
 {"正在按新模型重建超分……","Rebuilding DLSS Super Resolution with the new model..."},
 {"游戏超分当前：%s · DLSS %u.%u.%u","Game SR now: %s · DLSS %u.%u.%u"},
 {"游戏超分当前：%s","Game SR now: %s"},
 {"游戏还没开始用 DLSS 超分；进游戏画面后生效。","The game has not started DLSS Super Resolution yet; the choice applies once it does."},
 {"这个游戏自带的 DLSS 低于 310.5，用不了 M 和 L。","This game's DLSS is older than 310.5; M and L are unavailable."},
 {"NVIDIA App 或 Profile Inspector 也在给这个游戏设超分模型。","NVIDIA App or Profile Inspector also sets an SR model for this game."},
 {"超分模型没能切换，原来的模型保留。","The SR model could not be changed; the previous model stays."},
 {"超分模型已切换，但没能保存，下次进游戏会用回原来的。","SR model changed but not saved; the next start uses the previous one."},
 {"特调","Tuned"},
 {"启用033特调：一键换成 033 调好的整套参数（前置、SR、NR，超分模型 L、帧生成 6×；20、30 系超分模型用 K，帧生成倍率不动）。再点一下回到开启前你自己的设置。","Enable 033 tuning: one click to 033's tuned settings (color, SR, NR, SR model L, frame generation 6x; RTX 20/30 use SR model K and keep their multiplier). Click again to return to your own earlier settings."},
 {"033特调已启用。再点一下关闭，回到开启前你自己的设置；开启期间改过的参数不保留。","033 tuning is on. Click again to turn it off and return to your own earlier settings; changes made while it was on are not kept."},
 {"033特调的参数读不出来，没有开启。","033 tuning data could not be read; not enabled."},
 {"NR 现在没在运行，033特调没有开启。","NR is not running; 033 tuning was not enabled."},
 {"没能记下你现在的设置，033特调没有开启。","Your current settings could not be kept; 033 tuning was not enabled."},
 {"提交失败，033特调没有开启，原来的设置不变。","Submission failed; 033 tuning was not enabled and your settings are unchanged."},
 {"已启用 033特调，正在准备模型。","033 tuning on; preparing the model."},
 {"已关闭 033特调；开启前的设置没找到，当前参数保留。","033 tuning off; your earlier settings were not found, so the current ones stay."},
 {"033特调没能关闭，请稍后再试。","033 tuning could not be turned off; try again shortly."},
 {"NR 现在没在运行，033特调没有关闭。","NR is not running; 033 tuning was not turned off."},
 {"提交失败，033特调仍然开着。","Submission failed; 033 tuning stays on."},
 {"已关闭 033特调，回到开启前的设置，正在准备模型。","033 tuning off; back to your earlier settings, preparing the model."},
 {"设置已换回，但开关记录没能清掉，请再点一次关闭。","Settings restored, but the switch record could not be cleared; turn it off once more."},
 };
 for(const auto& p:pairs){if(!std::strcmp(text,p.zh)||!std::strcmp(text,p.en))return yyappearance::english?p.en:p.zh;}return text;
}
}
